fix build and boot

diff --git a/riscv/Makefile b/riscv/Makefile
--- a/riscv/Makefile
+++ b/riscv/Makefile
@@ -1,26 +1,37 @@
+ifndef  PREFIX
+PREFIX  := $(shell                                                           \
+	if riscv64-unknown-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo "riscv64-unknown-elf-";                                          \
+	elif riscv64-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1;       \
+	then echo "riscv64-elf-";                                                  \
+	else echo "***" 1>&2;                                                      \
+	echo "*** RISC-V GCC not found"; 1>&2;                                     \
+	echo "*** You can install it via `brew install riscv-elf-gcc`"; 1>&2;      \
+	exit 1;                                                                    \
+	fi)
+endif
+
+
 KERNEL  := kernel.elf
 LINKER  := kernel.ld
 
-CC      := riscv64-elf-gcc
-LD      := riscv64-elf-ld
-QEMU    := qemu-system-riscv64
 
-GDBPORT := $(shell expr `id -u` % 5000 + 25000)
-NCPU    := 2
+CC      := $(PREFIX)gcc
+LD      := $(PREFIX)ld
+OBJDUMP := $(PREFIX)objdump
+
 
 CFLAGS  :=                       \
 	-march=rv64gc                  \
+	-mabi=lp64d                    \
 	-nostdlib                      \
+	-nostartfiles                  \
+	-ffreestanding                 \
+	-fno-omit-frame-pointer        \
+	-fno-common                    \
+	-mcmodel=medany                \
 	-Wall                          \
 	-g
-
-
-QFLAGS  :=                       \
-  -machine virt                  \
-	-bios none                     \
-	-m 64M                         \
-	-smp $(NCPU)                   \
-	-nographic
 
 
 OFILES  :=                       \
@@ -40,7 +51,9 @@ all: $(KERNEL)
 
 $(KERNEL): $(OFILES) $(LINKER)
 	$(LD) -T $(LINKER) -o $@ $(OFILES)
+	$(OBJDUMP) -S $@ > $@.asm
+	$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $@.sym
 
 
-qemu-gdb: $(KERNEL)
-	$(QEMU) $(QFLAGS) -kernel $< -S -gdb tcp::$(GDBPORT)
+clean:
+	rm -f *.o *.d $(KERNEL) $(KERNEL).asm $(KERNEL).sym
